-- Baseline migration for public schema
-- Mirrors current tables in the existing database without making breaking changes.

-- Ensure required extensions exist for UUID generation
create extension if not exists "pgcrypto";

-- Goals table
create table if not exists public.goals (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  heading     text,
  description text
);

-- Email frequencies table
create table if not exists public.email_frequencies (
  id                  bigint generated by default as identity primary key,
  created_at          timestamptz not null default now(),
  time_interval_label text,
  interval_seconds    bigint
);

-- Users table (linked to auth.users)
create table if not exists public.users (
  id                 uuid not null default gen_random_uuid() primary key,
  created_at         timestamptz not null default now(),
  first_name         text,
  email              text,
  goal_id            bigint references public.goals (id),
  email_frequency_id bigint references public.email_frequencies (id),
  constraint users_id_fkey foreign key (id) references auth.users (id)
);

-- Journal entries table
create table if not exists public.journal_entries (
  id        bigint generated by default as identity primary key,
  user_id   uuid not null,
  content   text not null,
  created_at timestamptz not null default now(),
  constraint journal_entries_user_id_fkey foreign key (user_id) references public.users (id)
);

-- Enable Row Level Security to match current database state
alter table public.goals enable row level security;
alter table public.email_frequencies enable row level security;
alter table public.users enable row level security;
alter table public.journal_entries enable row level security;


